# Generated by Django 2.2.6 on 2019-12-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='img',
            field=models.ImageField(default='/product_images/default.png', upload_to='product_images'),
        ),
    ]
